build:
    nodes:
        analysis:
            environment:
                php: 7.2

    environment:
        mysql: 5.7

    project_setup:
        before:
            - mysql -e 'CREATE DATABASE IF NOT EXISTS test_db;'

    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage.colver'
                coverage:
                    file: 'coverage.colver'
                    format: 'clover'

filter:
    paths:
        - src/*